// script.js — vanilla JS for interactivity, animations, and form validation
// Author: Generated by assistant

document.addEventListener("DOMContentLoaded", () => {
  // Elements
  const hamburger = document.querySelector(".hamburger");
  const navMenu = document.querySelector(".nav-menu");
  const navLinks = document.querySelectorAll(".nav-link");
  const navbar = document.querySelector(".navbar");
  const skillProgress = document.querySelectorAll(".skill-progress");
  const fadeElements = document.querySelectorAll(".fade-in");

  // Hamburger toggle for mobile
  function toggleMenu() {
    hamburger.classList.toggle("active");
    navMenu.classList.toggle("active");
    // manage focus for accessibility
    if (navMenu.classList.contains("active")) {
      navMenu.setAttribute("aria-hidden", "false");
      hamburger.setAttribute("aria-expanded", "true");
    } else {
      navMenu.setAttribute("aria-hidden", "true");
      hamburger.setAttribute("aria-expanded", "false");
    }
  }

  if (hamburger) {
    hamburger.addEventListener("click", toggleMenu);
    hamburger.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") toggleMenu();
    });
  }

  // Close mobile menu when a nav link is clicked
  navLinks.forEach((link) => {
    link.addEventListener("click", () => {
      if (navMenu.classList.contains("active")) toggleMenu();
    });
  });

  // Navbar shadow on scroll
  window.addEventListener("scroll", () => {
    if (window.scrollY > 20) navbar.classList.add("scrolled");
    else navbar.classList.remove("scrolled");
  });

  document.querySelectorAll('a[href^="#"]').forEach((anchor) => {
    anchor.addEventListener("click", function (e) {
      const href = this.getAttribute("href");

      // ignore empty hash
      if (!href || href === "#" || href === "#!") return;

      // find target in current page
      const target = document.querySelector(href);

      // if target exists → smooth scroll
      if (target) {
        e.preventDefault();
        target.scrollIntoView({
          behavior: "smooth",
          block: "start",
        });
      }
      // else → let browser handle normally (external / other page)
    });
  });

  // Intersection Observer for fade-in elements
  const fadeObserver = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("visible");
        }
      });
    },
    { threshold: 0.15 }
  );
  fadeElements.forEach((el) => fadeObserver.observe(el));

  // Animate skill bars when visible
  const skillsSection = document.querySelector(".skills");
  if (skillsSection && skillProgress.length) {
    const skillsObserver = new IntersectionObserver(
      (entries, observer) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            skillProgress.forEach((bar) => {
              const value = bar.getAttribute("data-progress") || "0";
              bar.style.width = value + "%";
            });
            observer.disconnect();
          }
        });
      },
      { threshold: 0.25 }
    );
    skillsObserver.observe(skillsSection);
  }

  // Contact form client-side validation
  const form = document.getElementById("contact-form");
  const successBox = document.getElementById("form-success");

  function showError(groupEl, show) {
    if (show) groupEl.classList.add("error");
    else groupEl.classList.remove("error");
  }

  function validateEmail(email) {
    return /^\S+@\S+\.\S+$/.test(email);
  }

  if (form) {
    form.addEventListener("submit", (e) => {
      e.preventDefault();
      let valid = true;
      const name = form.querySelector("#name");
      const email = form.querySelector("#email");
      const message = form.querySelector("#message");

      // Name
      if (!name.value.trim()) {
        showError(document.getElementById("group-name"), true);
        valid = false;
      } else showError(document.getElementById("group-name"), false);

      // Email
      if (!validateEmail(email.value.trim())) {
        showError(document.getElementById("group-email"), true);
        valid = false;
      } else showError(document.getElementById("group-email"), false);

      // Message
      if (!message.value.trim() || message.value.trim().length < 10) {
        showError(document.getElementById("group-message"), true);
        valid = false;
      } else showError(document.getElementById("group-message"), false);

      if (!valid) return;

      // Simulate successful submission (replace with real API call)
      successBox.classList.add("show");
      // reset form
      form.reset();
      // hide success after 4s
      setTimeout(() => successBox.classList.remove("show"), 4000);
    });
  }
  // Slideshow Logic
  let slideIndices = {};

  window.plusSlides = function (n, slideshowId) {
    showSlides((slideIndices[slideshowId] += n), slideshowId);
  };

  function showSlides(n, slideshowId) {
    let i;
    let container = document.getElementById(slideshowId);
    if (!container) return;

    let slides = container.getElementsByClassName("slide");
    if (n > slides.length) {
      slideIndices[slideshowId] = 1;
    }
    if (n < 1) {
      slideIndices[slideshowId] = slides.length;
    }

    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }

    slides[slideIndices[slideshowId] - 1].style.display = "block";
  }

  // Initialize slideshows
  document.querySelectorAll(".slideshow-container").forEach((container) => {
    let id = container.id;
    slideIndices[id] = 1;
    showSlides(1, id);
  });
});

/* End of script.js */
